### PR TITLE
fixed kunsthalte donation page platforms bug

### PR DESCRIPTION
**Pull request by yhtyyar94**

### CODE REVIEW

**Review by MustafaTRKYLMZ — APPROVED** [review]

**Review by 7alip — CHANGES_REQUESTED** [review]
Screenshot 2023-08-06 at 18 11 12

**Review by 7alip — COMMENTED** [review]
@MustafaTRKYLMZ I'm not sure if Kunsthalte team wants to see other platforms in their website?

If the platforms will be listed in Kunsthalte donation page, should we redirect users to https://wsvvrijheid.nl/platforms or we show the pages in Kunsthalte website? Then we can merge this implementation.

**Comment by MustafaTRKYLMZ** [comment]
> @MustafaTRKYLMZ I'm not sure if Kunsthalte team wants to see other platforms in their website?
> 
> If the platforms will be listed in Kunsthalte donation page, should we redirect users to https://wsvvrijheid.nl/platforms or we show the pages in Kunsthalte website? Then we can merge this implementation.

You are right. Other platforms don't necessary in kunsthalte page.

**Comment by 7alip** [comment]
So, we should remove platforms from donation page as well as all platform related pages.

@yhtyyar94 sorry for the last time change.

**Review by 7alip — APPROVED** [review]
Thanks! It's ready to merge

**Pull request merged**
