### PR TITLE
Donation

### PR DESCRIPTION
**Pull request by 7alip**

### CODE REVIEW

**Comment by 7alip** [comment]
@yhtyyar94 Do you want to merge it?

**Comment by yhtyyar94** [comment]
yes sure thanks

**Review by yhtyyar94 — APPROVED** [review]

**Comment by MustafaTRKYLMZ** [comment]
Can you look dashboard donation page? @yhtyyar94 I think, link is wrong.Donation  page is opening in different website.

**Comment by 7alip** [comment]
> Can you look dashboard donation page? @yhtyyar94 I think, link is wrong.Donation page is opening in different website.

It renders in the same website but It seems the layout is not AdminLayout

**Pull request merged**
